### ISSUE TITLE
httpreq: unexpected status code: [status code: 400]

### ISSUE THREAD

**Issue by nsakkos** [canonical/httprequest-lego-k8s-operator#211] opened 2024-09-13 15:09 UTC
### Bug Description

While setting up httprequest-lego-k8s charm with nginx-ingress-integrator (v 24.2.0), we're getting a 400 error:
```

ERROR unit.httprequest-lego-k8s/0.juju-log     2024/09/13 14:08:27 [WARN] [XXX] acme: cleaning up failed: httpreq: unexpected status code: [status code: 400] body: <!doctype html>
ERROR unit.httprequest-lego-k8s/0.juju-log     <html lang="en">
ERROR unit.httprequest-lego-k8s/0.juju-log     <head>
ERROR unit.httprequest-lego-k8s/0.juju-log       <title>Bad Request (400)</title>
ERROR unit.httprequest-lego-k8s/0.juju-log     </head>
ERROR unit.httprequest-lego-k8s/0.juju-log     <body>
ERROR unit.httprequest-lego-k8s/0.juju-log       <h1>Bad Request (400)</h1><p></p>
ERROR unit.httprequest-lego-k8s/0.juju-log     </body>
ERROR unit.httprequest-lego-k8s/0.juju-log     </html>
ERROR unit.httprequest-lego-k8s/0.juju-log     2024/09/13 14:08:27 [INFO] Deactivating auth: `https://acme-v02.api.letsencrypt.org/XXX`
ERROR unit.httprequest-lego-k8s/0.juju-log     2024/09/13 14:08:27 Could not obtain certificates:
ERROR unit.httprequest-lego-k8s/0.juju-log     	error: one or more domains had a problem:
```

How can I resolve this?

### To Reproduce

juju deploy httprequest-lego-k8s
juju config httprequest-lego-k8s
juju integrate httprequest-lego-k8s nginx-ingress-integrator

### Environment

httprequest-lego-k8s charm is  channel latest/stable , rev  83
Juju controller is 3.5.3, deployed on PS6

### Relevant log output

```shell
https://pastebin.canonical.com/p/YRMy5VRZGZ/
```

**Comment by DanielArndt** [comment] 2024-09-17 17:53
Hi @nsakkos , I'll do my best to help here, but just a heads up I'm only familiar with this charm at a high level, so bear with me.

It looks to me like the [Challenge Solver](https://charmhub.io/httprequest-lego-k8s/docs/h-reference-dns-agent) is the thing throwing the error.  This would be whatever you set for `httpreq_endpoint` in the charm config.

Are you sure that is configured and working correctly? I would presume there are some logs on that service that might help us narrow down what the issue is.

**Comment by DanielArndt** [comment] 2024-09-25 11:18
Hi @nsakkos -- I just wanted to bump this and see if you were able to resolve your issue or if you still need any help?

**Comment by DanielArndt** [comment] 2024-10-01 11:51
It has been a couple weeks and we don't have enough information to move forward, so I am closing this.

@nsakkos if this becomes an issue again in the future, please feel free to re-open or create a new issue.

**Closed by DanielArndt** 2024-10-01 11:51 UTC
Labels: bug
