### ISSUE TITLE
Certificates generated by the charm don't include intermediates

### ISSUE THREAD

**Issue by mthaddon** [canonical/httprequest-lego-k8s-operator#93] opened 2024-03-13 09:10 UTC
#### Describe the bug

It looks like the certificates generated by the charm don't include intermediates, so fail to pass verification by `curl`, for instance. They seem to be accepted by browsers (Chrome and Firefox have been tested) but nonetheless the intermediates are missing.

#### To Reproduce

1. Get a certificate from Let's Encrypt using this charm
2. Run `curl https://${hostname} -v`.
3. See the error.

#### Expected behavior

The generated certificate passes validation.

#### Screenshots

N/A

#### Logs

As an example:

```
$ curl 'https://cos-ps6.admin.canonical.com' -v
*   Trying 162.213.35.33:443...
* Connected to cos-ps6.admin.canonical.com (162.213.35.33) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.0 (OUT), TLS header, Certificate Status (22):
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.2 (IN), TLS header, Certificate Status (22):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS header, Finished (20):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.2 (IN), TLS header, Supplemental data (23):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS header, Unknown (21):
* TLSv1.3 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

#### Environment

- Charm / library version (if relevant): revision 40 of latest/stable
- Juju version (output from `juju --version`): 3.1.6
- Cloud Environment: OpenStack
- Kubernetes version (output from `kubectl version --short`): Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.7

#### Additional context

N/A

**Comment by ghislainbourgeois** [comment] 2024-03-13 17:27
The way the `tls-certificates-interface` works is by returning the CSR, certificate, CA certificate and chain as separate fields in the relation data, and in the `CertificateAvailable`. All those fields contain a single PEM string, except the chain field that contains a list of PEM strings, representing the whole chain, starting from the root CA.

Did you try to use the chain field? If this is something that would be useful, we could add an helper function to the library to construct the PEM string for the whole chain, or with only the certificate and intermediate CAs.

If on the other hand the chain field does not contain the full chain, we have a more serious issue to investigate.

**Comment by mthaddon** [comment] 2024-03-14 11:33
I do see a `chain` field in the relation data, sounds like this could be an issue on the charm that's relating to httprequest-lego-k8s (in this case traefik-k8s). I'll pull in someone from the Observability team to confirm.

**Comment by ghislainbourgeois** [comment] 2024-03-26 01:00
We have added helper methods to get the full chain in a PEM file format to the library in https://github.com/canonical/tls-certificates-interface/pull/141

This will need to be implemented in requirers like `traefik-k8s`. I will close this issue as the problem is not related to this charm.

**Closed by ghislainbourgeois** 2024-03-26 01:00 UTC
Labels: bug
